
CREATE DATABASE  IF NOT EXISTS Delta_app;
USE Delta_app;

CREATE TABLE user(
    id VARCHAR(50) PRIMARY KEY,
    username VARCHAR(50) UNIQUE,
    email VARCHAR(70) UNIQUE NOT NULL,
    password VARCHAR(50) NOT NULL
);

